theme: jekyll-theme-minimal
title: WORTH: A Framework for Context-Driven Technology Decisions
description: A pragmatic approach to cutting through dogma and making engineering choices that deliver real valu
